### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by pratimugale** [sayonpalit2599/parallelized-apriori-data-mining#1]
Hi, thanks for the code!
I get an error during compilation: https://pastebin.com/Z1MdJKaR
Please check what might be causing the issue.

**Comment by sayonpalit** [comment]
Hi @pratimugale so looks like an issue with your compiler `undefined reference to  std::cout'`  ,probably check if you have bits/stdc++ on your machine.Since it's a compiler issue I would ask you to look at websites like [stackoverflow](https://stackoverflow.com/) etc which would be more helpful in such cases.
